---
- name: Install Docker
  hosts: ubuntu_servers
  become: true

  tasks:
    - name: Install Docker packages
      apt:
        name:
          - docker.io
        state: present
        update_cache: true

    - name: Enable and start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      user:
        name: chris
        groups: docker
        append: true
