---
- name: Deploy Node Exporter
  hosts: ubuntu_servers
  become: true

  tasks:

    - name: Remove existing Node Exporter container if present
      command: docker rm -f node-exporter
      ignore_errors: true

    - name: Deploy Node Exporter container
      command: >
        docker run -d
        --name node-exporter
        --restart unless-stopped
        -p 9100:9100
        prom/node-exporter:latest
